version: 2
updates:
  - package-ecosystem: pip
    directory: /src/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: weekly
    groups:
      documentation-dependencies:
        patterns: ["*"]
    labels: [documentation]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
